angular.module('OrderCloud-HamburgerNavigation', []);

angular.module('OrderCloud-HamburgerNavigation')
    .directive('hamburgernavigation', hamburgernavigation)
    //.controller('HamburgerNavigationCtrl', HamburgerNavigationCtrl)
;

//hamburgernavigation.$inject = ['$scope'];
function hamburgernavigation() {
    var directive = {
        restrict: 'E',
        /* scope: {
         user: "="
         },*/
        template: template,
        controller: 'NavCtrl'
    };
    return directive;

    function template() {
        return [
            '<style>',
            '.navbar.navbar-hamburger { min-height:40px; max-height:40px; background-color: #011e41; padding-bottom:10px; }',
            '.navbar-hamburger .col-collapse { background-color:#fff; color:#fff; }',
            '.navbar-hamburger i { font-size: 1.8em; left: 10px; position: relative; top: 10px; }',
            '.navbar-hamburger a, ul.burgers li a { color:#ffffff; text-decoration:none; }',
            '.navbar-hamburger a:hover { color:#fff; text-decoration:none; }',
            'ul.burgers { background-color: #011e41; margin-bottom:20px; }',
            'ul.burgers li a { background-color: #011e41;  padding: 0.5em 0.75em; width: 100%; }',
            'ul.burgers li.active a { background-color: #ffb81d; color: #01214f; text-decoration:none;}',
            'ul.burgers li a:hover { background-color:#0f4a78; color: #fff; text-decoration:none;}',
            'ul.burgers li a:focus { background-color: #ffb81d; color: #01214f; text-decoration:none;}',
            'ul.burgers li a i { min-width:20px; }',
            'ul.burgers li ul li a i { min-width:25px; }',
            '.navbar-account { min-height:40px; max-height:40px; background-color: #011e41; padding-bottom:10px; }',
            '.navbar-help { min-height:40px; max-height:40px; background-color: #011e41; padding-bottom:10px; }',
            '.navbar-faculty { min-height:40px; max-height:40px; background-color: #011e41; padding-bottom:10px; }',
            'ul.my-account li a, ul.help li a, ul.faculty li a { font-size:95%; text-indent:5px; }',
            '</style>',
            '<header class="header navbar navbar-inner hidden-md hidden-lg">',
            '<nav class="navbar navbar-hamburger" role="navigation">',
            '<div ng-init="isCollapsed = true">',
            '<a ng-click="isCollapsed = !isCollapsed" ng-class="{\'active\': !isCollapsed, \'\': isCollapsed}">',
            '<span><i class="fa fa-th-list"></i></span>',
            '</a>',
            '</div>',
            '</nav>',
            '<div class="col-xs-12 col-collapse" collapse="isCollapsed">',
            '<ul class="burgers">',
            '<li ng-class="{\'active\': isActive([\'catalog\'])}">',
            '<a href="catalog">',
            '<i class="fa fa-home"></i>',
            '<span>{{\'Home\' | r | xlat}}</span>',
            '</a>',
            '</li>',
            //account
            '<li id="account">',
            '<nav class="navbar-account" role="navigation">',
            '<div ng-init="isCollapsedAccount = true">',
            '<a ng-click="isCollapsedAccount = !isCollapsedAccount" ng-class="{\'active\': !isCollapsedAccount, \'\': isCollapsedAccount}">',
            '<i class="fa fa-cog" ng-show="isCollapsedAccount"></i>',
            '<i class="fa fa-cogs" ng-show="!isCollapsedAccount"></i>',
            '<span>{{\'My Account\' | r | xlat}}</span>',
            '</a>',
            '</div>',
            '</nav>',
            '<div class="col-xs-12 col-collapse" collapse="isCollapsedAccount">',
            '<ul class="my-account">',
            '<li ng-show="user.Type != \'Customer\'">',
            '<a href="login">',
            '<i class="fa fa-sign-in"></i>',
            '<span>{{\'Login\' | r | xlat}}</span>',
            '</a>',
            '</li>',
            '<li ng-show="user.Type != \'Customer\'">',
            '<a href="admin">',
            '<i class="fa fa-user-plus"></i>',
            '<span>{{\'New User\' | r | xlat}}</span>',
            '</a>',
            '</li>',
            '<li ng-show="user.Type == \'Customer\' && user.Permissions.contains(\'ViewSelfAdmin\')">',
            '<a href="admin">',
            '<i class="fa fa-user"></i>',
            '<span>{{\'User Information\' | r | xlat}}</span>',
            '</a>',
            '</li>',
            '<li ng-if="user.Type == \'Customer\'" ng-class="{\'active\': isActive([\'orders\'])}">',
            '<a href="order">',
            '<i class="fa fa-clipboard"></i>',
            '<span>{{\'Orders\' | r | xlat}}</span>',
            '</a>',
            '</li>',
            '<li ng-show="user.Type == \'Customer\' && (user.Permissions.contains(\'CreateShipToAddress\') || user.Permissions.contains(\'CreateBillToAddress\'))" class="addresses">',
            '<a href="addresses">',
            '<i class="fa fa-book"></i>',
            '{{\'Addresses\' | r | xlat}}',
            '</a>',
            '</li>',
            '<li ng-show="user.Type == \'Customer\' && user.Permissions.contains(\'ViewMessaging\')" class="messages">',
            '<a href="message">',
            '<i class="fa fa-comment"></i>',
            '{{\'Messages\' | r | xlat}}',
            '</a>',
            '</li>',
            '<li class="favorites" ng-show="user.Type == \'Customer\'">',
            '<a href="favoriteorders">',
            '<i class="fa fa-star"></i>',
            '{{\'Favorites\' | r | xlat}}',
            '</a>',
            '</li>',
            '<li class="report" ng-if="user.Type == \'Customer\' && user.Permissions.contains(\'AdvancedReporting\')" ng-class="{\'active\': isActive(\'reports\')}">',
            '<a href="reports">',
            '<i class="fa fa-bar-chart-o"></i>',
            '{{\'Reports\' | r | xlat}}',
            '</a>',
            '</li>',
            '<li>',
            '<a href="#" neworder ng-if="user.Permissions.contains(\'MultipleShoppingCart\') && currentOrder" class="neworder" ng-click="newOrderLoadingIndicator = true;startNewOrder()">',
            '<i class="fa fa-plus"></i>',
            '{{\'Start\' | r | xlat}} {{\'New\' | r | xlat}} {{\'Order\' | r | xlat}}',
            '</a>',
            '</li>',
            '<li ng-if="user.Type ==\'Customer\' && user.Groups[0].Name != \'FacultyStaff\'">',
            '<a href="#" class="451_btn_logout" ng-click="Logout()">',
            '<i class="fa fa-sign-out"></i>',
            '<span>{{\'Logout\' | r | xlat}}</span>',
            '</a>',
            '</li>',
            '</ul>',
            '</div>',
            '</li>',
            //faculty anon
            '<li class="faculty-login" ng-show="(user.Type == \'TempCustomer\' || user.Type != \'TempCustomer\' && user.Groups[0].Name != \'FacultyStaff\')">',
            '<a href="https://sso.umuc.edu/idp/profile/SAML2/Unsolicited/SSO?providerId=https://umucauth.tela.com/shibboleth&shire=https://umucauth.tela.com/Shibboleth.sso/SAML2/POST">',
            '<i class="fa fa-lock"></i>',
            '<span>{{\'Faculty/Staff Login \' | r | xlat}}</span>',
            '</a>',
            '</li>',
            //faculty authenticated
            '<li class="faculty-login" ng-show="user.Groups[0].Name == \'FacultyStaff\'">',
            '<a href="#" class="451_btn_logout" ng-click="Logout()">',
            '<i class="fa fa-unlock"></i>',
            '<span>{{\'Faculty/Staff Logout \' | r | xlat}}</span>',
            '</a>',
            '</li>',
            //help
            '<li id="help">',
            '<nav class="navbar-help" role="navigation">',
            '<div ng-init="isCollapsedHelp = true">',
            '<a ng-click="isCollapsedHelp = !isCollapsedHelp" ng-class="{\'active\': !isCollapsedHelp, \'\': isCollapsedHelp}">',
            '<i class="fa fa-info" ng-show="isCollapsedHelp"></i>',
            '<i class="fa fa-info-circle" ng-show="!isCollapsedHelp" style="position:relative; left:-3px;"></i>',
            '<span>{{\'Help\' | r | xlat}}</span>',
            '</a>',
            '</div>',
            '</nav>',
            '<div class="col-xs-12 col-collapse" collapse="isCollapsedHelp">',
            '<ul class="help">',
            '<li>',
            '<faqmodal></faqmodal>',
            '</li>',
            '<li>',
            '<contactmodal></contactmodal>',
            '</li>',
            '</ul>',
            '</div>',
            '</li>',


            //search
            '<li id="search" ng-class="{\'active\': isActive([\'search\'])}">',
            '<a href="search">',
            '<i class="fa fa-search"></i>',
            '<span>{{\'Search\' | r | xlat}}</span>',
            '</a>',
            '</li>',


            //cart
            '<li class="cart" ng-class="{\'active\': isActive([\'cart\', \'checkout\'])}">',
            '<a class="cart" href="cart">',
            '<i class="fa fa-shopping-cart"></i>',
            '<span>{{\'Cart\' | r | xlat}}</span>',
            '</a>',
            '</li>',
            '</ul>',
            '</div>',
            '</header>'
        ].join('');
    }
}